name = "MoreMaps"
uuid = "d6ea422f-1f55-4be1-bfc3-e7c09aa4d855"
authors = ["brendanjohnharris <bhar9988@uni.sydney.edu.au> and contributors"]
version = "0.2.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[weakdeps]
Dagger = "d58978e5-989f-55fb-8d15-ea34adc7bf54"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[extensions]
DaggerExt = ["Dagger"]
ProgressLoggingExt = ["ProgressLogging", "UUIDs"]
TermExt = ["Term"]

[compat]
Dagger = "0.19"
Distributed = "1.10"
ProgressLogging = "0.1"
Term = "2"
UUIDs = "1.10"
julia = "1.10"
